### ISSUE TITLE
Access denied due to data localization enabled when using Europe hub

### ISSUE THREAD

**Issue by jose-bernard-receeve** [LambdaTest/node-rest-client#15]
I started to use this package from Germany and my test account was located in the US but when I started using my organization credentials it started to fail with the following error

`Access denied due to data localization enabled`

```typescript
   const GRID_HOST = "hub-eu.lambdatest.com/wd/hub";
   capabilities["LT:Options"].name = testName;
   capabilities["LT:Options"].tags = tags;

   this.driver = new Builder().usingServer(`https://${LAMBDATEST_USERNAME}:${LAMBDATEST_KEY}@${GRID_HOST}`).withCapabilities(capabilities).build();

    this.automationClient = LambdaTestRestClient.AutomationClient({
      username: LAMBDATEST_USERNAME,
      accessKey: LAMBDATEST_KEY,
    });
```

Digging a bit in the code I noticed the api base URL is `api.lambdatest.com`, should this be `eu-api.lambdatest.com` for the EU hub? I see both resolve to the same IP address.

The error occurs when I try to set the session status

```typescript
  async updateJob(sessionId: string | null, status: string): Promise<void> {
    return new Promise((resolve, reject) => {
      this.automationClient.updateSessionById(sessionId, { status_ind: status }, (err: Error) => {
        if (err) return reject(err);
        return resolve();
      });
    });
  }
  ```

Thanks in advance!

**Comment by jose-bernard-receeve** [comment]
I modified the `config.js` file manually in the `node_modules` and appended `eu` to the base URL, I'm not getting the error anymore

**Comment by Shahnawaz-Sk** [comment]
@jose-bernard-receeve We will look into this issue and will fix this. Thank you for raising this.

**Comment by Shahnawaz-Sk** [comment]
@jose-bernard-receeve We have added a [pull request](https://github.com/LambdaTest/node-rest-client/pull/18) containing the fix by referencing your [pull request](https://github.com/LambdaTest/node-rest-client/pull/17). This should address the use case. Thanks.

**Comment by jose-bernard-receeve** [comment]
Thanks! it works now
