### ISSUE TITLE
Dependency `request` is deprecated and has a vulnerability

### ISSUE THREAD

**Issue by karanb0** [LambdaTest/node-rest-client#9]
Our team uses [wdio-lambdatest-service](https://www.npmjs.com/package/wdio-lambdatest-service) which imports `node-rest-client`. One of the dependencies used by `node-rest-client` – [request](https://github.com/LambdaTest/node-rest-client/blob/master/package.json#L29 ) – is [deprecated](https://www.npmjs.com/package/request) and has a [vulnerability](https://github.com/request/request/issues/3442) which doesn't look like it's going to be addressed.

Repro: `npm audit`
<img width="635" alt="Screenshot 2023-05-03 at 3 06 29 PM" src="https://user-images.githubusercontent.com/16848789/236018651-54b52462-e1fb-45e0-8cae-856630d363ca.png">

Possible solutions:
* Consider replacing usage of `request` with another well supported package: eg. [axios](https://www.npmjs.com/package/axios), [got](https://www.npmjs.com/package/got), [node-fetch](https://www.npmjs.com/package/node-fetch)

**Comment by jobicoppola** [comment]
Fwiw we are trying to implement LambdaTest and running into this issue also, as the vulnerability [is in Snyk also](https://security.snyk.io/vuln/SNYK-JS-REQUEST-3361831) and causing our Snyk checks to fail.

Are there any plans to move away from using `request`?

**Comment by stackptr** [comment]
Also interested in progress on replacing this deprecated dependency.

**Comment by Shahnawaz-Sk** [comment]
thanks for the concern, we will look into this.

**Comment by Shivanshu-lambdatest** [comment]
@karanb0 you can use wdio-lambdatest-service. From the latest version of wdio-lambdatest-service, we have removed the usage of node-rest-client to remove the vulnerability.
